Make overlay area payload compatible with real api
peaceflat/spatial_id_viewer pull request #15
Opened 2024-10-18 14:53 UTC by Thiniraxz

2024-11-04 15:34 UTC, Thiniraxz commented
Make overlay area payload compatible with real api 
Integration for get-object compatible with real api stream response
Reservation route file upload

2024-11-06 17:07 UTC, Rishy20 requested changes

2024-11-06 17:07 UTC, Rishy20 commented on packages/spatial-id-viewer/src/views/reserved-routes/create/index.tsx
> +    console.log(authInfo);
remove console log

2024-11-06 17:07 UTC, Rishy20 commented on packages/spatial-id-viewer/src/views/reserved-routes/create/index.tsx
> +      console.log(jsonData);
remove console log

2024-11-06 18:55 UTC, Rishy20 approved these changes

2024-11-06 18:55 UTC, merged